/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ["introduction/overview", "introduction/installation", "introduction/faq", "introduction/quickstart-guide"],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: ["tutorials/vs-code-dev-containers", "tutorials/apps-in-kubernetes-upgrade"],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'How-to Guides',
      items: ["how-to-guides/private-registries", "how-to-guides/managing-images", "how-to-guides/running-containers", "how-to-guides/overriding-mac-and-linux-config"],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Reference Guides',
      items: ["references/architecture", "references/preferences", "references/docker-cli-and-dockerd", "references/containerd-and-nerdctl", "references/troubleshooting"],
      collapsed: false,
    },
  ],   
};

module.exports = sidebars;
