/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        "getting-started/introduction",
        "getting-started/installation",
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        "tutorials/working-with-images",
        "tutorials/working-with-containers",
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'How-to Guides',
      items: [
        "how-to-guides/hello-world-example",
        "how-to-guides/transfer-container-images",
        "how-to-guides/create-multi-node-cluster",
        "how-to-guides/setup-NGINX-Ingress-Controller",
        "how-to-guides/vs-code-docker",
        "how-to-guides/vs-code-remote-containers",
        "how-to-guides/rancher-on-rancher-desktop",
        "how-to-guides/skaffold-and-rancher-desktop",
        "how-to-guides/provisioning-scripts",
        "how-to-guides/running-air-gapped"
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'References',
      items: [
        "references/architecture",
        "references/rdctl-command-reference",
        {
          type: 'category',
          label: 'Features',
          items: [
            "references/features/general",
            "references/features/port-forwarding",
            "references/features/images",
            "references/features/troubleshooting",
            "references/features/diagnostics",
          ],
        },
        {
          type: 'category',
          label: 'Preferences',
          items: [
            "references/preferences/application",
            "references/preferences/virtual-machine",
            "references/preferences/wsl",
            "references/preferences/container-engine",
            "references/preferences/kubernetes",
          ],
        },
        "references/dependency-versions"
      ],
      collapsed: true,
    },
    "faq",
    "troubleshooting-tips"
  ],
};

module.exports = sidebars;
